#!/bin/bash
echo $1
if [ "$1" != "" -a -f "$1" ]; then
    adb pull /sdcard/AnkuLua/ffbe_trust/$1
else
    for lua in `ls -1 *.lua`
    do
        echo
        echo $lua
        adb pull /sdcard/AnkuLua/ffbe_trust/$lua
    done
fi
