#!/bin/bash
if [ "$1" != "" ]; then
    if [ -f "$1" ]; then
        echo $1
        adb push $1 //sdcard/AnkuLua/ffbe_trust/`dirname $1`
    else
        echo "\"$1\" does not exist"
    fi
else
    for lua in `ls -1 *.lua`
    do
        echo
        echo $lua
        adb push $lua //sdcard/AnkuLua/ffbe_trust/
    done
fi
